// packages/ui/solidjs/src/components/dropdown-menu.tsx
import * as DropdownMenuPrimitive from "@kobalte/core/dropdown-menu";
import type { PolymorphicProps } from "@kobalte/core/polymorphic";
import { Check, ChevronRight } from "lucide-solid";
import type { ComponentProps, ValidComponent } from "solid-js";
import { mergeProps, splitProps } from "solid-js";

import { cn } from "@/libs/utils";

type DropdownMenuProps = DropdownMenuPrimitive.DropdownMenuRootProps;

const DropdownMenu = (props: DropdownMenuProps) => {
	const mergedProps = mergeProps({ gutter: 4 }, props);
	return <DropdownMenuPrimitive.Root data-slot="dropdown-menu" {...mergedProps} />;
};

type DropdownMenuPortalProps = DropdownMenuPrimitive.DropdownMenuPortalProps;

const DropdownMenuPortal = (props: DropdownMenuPortalProps) => (
	<DropdownMenuPrimitive.Portal data-slot="dropdown-menu-portal" {...props} />
);

type DropdownMenuTriggerProps<T extends ValidComponent = "button"> = PolymorphicProps<
	T,
	DropdownMenuPrimitive.DropdownMenuTriggerProps<T>
> &
	Pick<ComponentProps<T>, "class">;

const DropdownMenuTrigger = <T extends ValidComponent = "button">(
	props: DropdownMenuTriggerProps<T>,
) => {
	const [local, others] = splitProps(props as DropdownMenuTriggerProps, ["class"]);
	return (
		<DropdownMenuPrimitive.Trigger
			class={local.class}
			data-slot="dropdown-menu-trigger"
			{...others}
		/>
	);
};

type DropdownMenuContentProps<T extends ValidComponent = "div"> = PolymorphicProps<
	T,
	DropdownMenuPrimitive.DropdownMenuContentProps<T>
> &
	Pick<ComponentProps<T>, "class">;

const DropdownMenuContent = <T extends ValidComponent = "div">(
	props: DropdownMenuContentProps<T>,
) => {
	const [local, others] = splitProps(props as DropdownMenuContentProps, ["class"]);
	return (
		<DropdownMenuPrimitive.Portal>
			<DropdownMenuPrimitive.Content
				class={cn(
					"z-50 z-dropdown-menu-content z-menu-target max-h-(--kb-popper-available-height) min-w-32 origin-(--kb-menu-content-transform-origin) overflow-y-auto overflow-x-hidden outline-none data-closed:overflow-hidden",
					local.class,
				)}
				data-slot="dropdown-menu-content"
				{...others}
			/>
		</DropdownMenuPrimitive.Portal>
	);
};

type DropdownMenuGroupProps<T extends ValidComponent = "div"> = PolymorphicProps<
	T,
	DropdownMenuPrimitive.DropdownMenuGroupProps<T>
> &
	Pick<ComponentProps<T>, "class">;

const DropdownMenuGroup = <T extends ValidComponent = "div">(props: DropdownMenuGroupProps<T>) => {
	const [local, others] = splitProps(props as DropdownMenuGroupProps, ["class"]);
	return (
		<DropdownMenuPrimitive.Group class={local.class} data-slot="dropdown-menu-group" {...others} />
	);
};

type DropdownMenuLabelProps<T extends ValidComponent = "span"> = PolymorphicProps<
	T,
	DropdownMenuPrimitive.DropdownMenuGroupLabelProps<T>
> &
	Pick<ComponentProps<T>, "class"> & {
		inset?: boolean;
	};

const DropdownMenuLabel = <T extends ValidComponent = "span">(props: DropdownMenuLabelProps<T>) => {
	const [local, others] = splitProps(props as DropdownMenuLabelProps, ["class", "inset"]);
	return (
		<DropdownMenuPrimitive.GroupLabel
			class={cn("z-dropdown-menu-label data-inset:pl-8", local.class)}
			data-inset={local.inset}
			data-slot="dropdown-menu-label"
			{...others}
		/>
	);
};

type DropdownMenuItemProps<T extends ValidComponent = "div"> = PolymorphicProps<
	T,
	DropdownMenuPrimitive.DropdownMenuItemProps<T>
> &
	Pick<ComponentProps<T>, "class"> & {
		inset?: boolean;
		variant?: "default" | "destructive";
	};

const DropdownMenuItem = <T extends ValidComponent = "div">(rawProps: DropdownMenuItemProps<T>) => {
	const props = mergeProps({ variant: "default" } as DropdownMenuItemProps<T>, rawProps);
	const [local, others] = splitProps(props as DropdownMenuItemProps, ["class", "inset", "variant"]);
	return (
		<DropdownMenuPrimitive.Item
			class={cn(
				"group/dropdown-menu-item relative z-dropdown-menu-item flex cursor-default select-none items-center outline-hidden data-disabled:pointer-events-none data-inset:pl-8 data-disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
				local.class,
			)}
			data-inset={local.inset}
			data-slot="dropdown-menu-item"
			data-variant={local.variant}
			{...others}
		/>
	);
};

type DropdownMenuSubProps = DropdownMenuPrimitive.DropdownMenuSubProps;

const DropdownMenuSub = (props: DropdownMenuSubProps) => (
	<DropdownMenuPrimitive.Sub data-slot="dropdown-menu-sub" {...props} />
);

type DropdownMenuSubTriggerProps<T extends ValidComponent = "div"> = PolymorphicProps<
	T,
	DropdownMenuPrimitive.DropdownMenuSubTriggerProps<T>
> &
	Pick<ComponentProps<T>, "class" | "children"> & {
		inset?: boolean;
	};

const DropdownMenuSubTrigger = <T extends ValidComponent = "div">(
	props: DropdownMenuSubTriggerProps<T>,
) => {
	const [local, others] = splitProps(props as DropdownMenuSubTriggerProps, [
		"class",
		"inset",
		"children",
	]);
	return (
		<DropdownMenuPrimitive.SubTrigger
			class={cn(
				"z-dropdown-menu-sub-trigger flex cursor-default select-none items-center outline-hidden data-inset:pl-8 [&_svg]:pointer-events-none [&_svg]:shrink-0",
				local.class,
			)}
			data-inset={local.inset}
			data-slot="dropdown-menu-sub-trigger"
			{...others}
		>
			{local.children}
			<ChevronRight class="ml-auto" />
		</DropdownMenuPrimitive.SubTrigger>
	);
};

type DropdownMenuSubContentProps<T extends ValidComponent = "div"> = PolymorphicProps<
	T,
	DropdownMenuPrimitive.DropdownMenuSubContentProps<T>
> &
	Pick<ComponentProps<T>, "class">;

const DropdownMenuSubContent = <T extends ValidComponent = "div">(
	props: DropdownMenuSubContentProps<T>,
) => {
	const [local, others] = splitProps(props as DropdownMenuSubContentProps, ["class"]);
	return (
		<DropdownMenuPrimitive.Portal>
			<DropdownMenuPrimitive.SubContent
				class={cn(
					"z-50 z-dropdown-menu-sub-content z-menu-target max-h-(--kb-popper-available-height) min-w-32 origin-(--kb-menu-content-transform-origin) overflow-y-auto overflow-x-hidden outline-none data-closed:overflow-hidden",
					local.class,
				)}
				data-slot="dropdown-menu-sub-content"
				{...others}
			/>
		</DropdownMenuPrimitive.Portal>
	);
};

type DropdownMenuCheckboxItemProps<T extends ValidComponent = "div"> = PolymorphicProps<
	T,
	DropdownMenuPrimitive.DropdownMenuCheckboxItemProps<T>
> &
	Pick<ComponentProps<T>, "class" | "children">;

const DropdownMenuCheckboxItem = <T extends ValidComponent = "div">(
	props: DropdownMenuCheckboxItemProps<T>,
) => {
	const [local, others] = splitProps(props as DropdownMenuCheckboxItemProps, ["class", "children"]);
	return (
		<DropdownMenuPrimitive.CheckboxItem
			class={cn(
				"relative z-dropdown-menu-checkbox-item flex cursor-default select-none items-center outline-hidden data-disabled:pointer-events-none data-disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
				local.class,
			)}
			data-slot="dropdown-menu-checkbox-item"
			{...others}
		>
			<span
				class="pointer-events-none z-dropdown-menu-item-indicator"
				data-slot="dropdown-menu-checkbox-item-indicator"
			>
				<DropdownMenuPrimitive.ItemIndicator>
					<Check />
				</DropdownMenuPrimitive.ItemIndicator>
			</span>
			{local.children}
		</DropdownMenuPrimitive.CheckboxItem>
	);
};

type DropdownMenuRadioGroupProps<T extends ValidComponent = "div"> = PolymorphicProps<
	T,
	DropdownMenuPrimitive.DropdownMenuRadioGroupProps<T>
> &
	Pick<ComponentProps<T>, "class">;

const DropdownMenuRadioGroup = <T extends ValidComponent = "div">(
	props: DropdownMenuRadioGroupProps<T>,
) => {
	const [local, others] = splitProps(props as DropdownMenuRadioGroupProps, ["class"]);
	return (
		<DropdownMenuPrimitive.RadioGroup
			class={local.class}
			data-slot="dropdown-menu-radio-group"
			{...others}
		/>
	);
};

type DropdownMenuRadioItemProps<T extends ValidComponent = "div"> = PolymorphicProps<
	T,
	DropdownMenuPrimitive.DropdownMenuRadioItemProps<T>
> &
	Pick<ComponentProps<T>, "class" | "children">;

const DropdownMenuRadioItem = <T extends ValidComponent = "div">(
	props: DropdownMenuRadioItemProps<T>,
) => {
	const [local, others] = splitProps(props as DropdownMenuRadioItemProps, ["class", "children"]);
	return (
		<DropdownMenuPrimitive.RadioItem
			class={cn(
				"relative z-dropdown-menu-radio-item flex cursor-default select-none items-center outline-hidden data-disabled:pointer-events-none data-disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
				local.class,
			)}
			data-slot="dropdown-menu-radio-item"
			{...others}
		>
			<span
				class="pointer-events-none z-dropdown-menu-item-indicator"
				data-slot="dropdown-menu-radio-item-indicator"
			>
				<DropdownMenuPrimitive.ItemIndicator>
					<Check />
				</DropdownMenuPrimitive.ItemIndicator>
			</span>
			{local.children}
		</DropdownMenuPrimitive.RadioItem>
	);
};

type DropdownMenuSeparatorProps<T extends ValidComponent = "hr"> = PolymorphicProps<
	T,
	DropdownMenuPrimitive.DropdownMenuSeparatorProps<T>
> &
	Pick<ComponentProps<T>, "class">;

const DropdownMenuSeparator = <T extends ValidComponent = "hr">(
	props: DropdownMenuSeparatorProps<T>,
) => {
	const [local, others] = splitProps(props as DropdownMenuSeparatorProps, ["class"]);
	return (
		<DropdownMenuPrimitive.Separator
			class={cn("z-dropdown-menu-separator", local.class)}
			data-slot="dropdown-menu-separator"
			{...others}
		/>
	);
};

type DropdownMenuShortcutProps = ComponentProps<"span">;

const DropdownMenuShortcut = (props: DropdownMenuShortcutProps) => {
	const [local, others] = splitProps(props, ["class"]);
	return (
		<span
			class={cn("z-dropdown-menu-shortcut", local.class)}
			data-slot="dropdown-menu-shortcut"
			{...others}
		/>
	);
};

export {
	DropdownMenu,
	DropdownMenuCheckboxItem,
	DropdownMenuContent,
	DropdownMenuGroup,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuPortal,
	DropdownMenuRadioGroup,
	DropdownMenuRadioItem,
	DropdownMenuSeparator,
	DropdownMenuShortcut,
	DropdownMenuSub,
	DropdownMenuSubContent,
	DropdownMenuSubTrigger,
	DropdownMenuTrigger,
};

// packages/proto/ui/src/dropdown-menu.tsx
"use client";

import { cn } from "@de100/ui-proto";
import { CheckIcon, ChevronRightIcon, DotFilledIcon } from "@radix-ui/react-icons";
import { DropdownMenu as DropdownMenuPrimitive } from "radix-ui";

export function DropdownMenu({
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Root>) {
	return <DropdownMenuPrimitive.Root data-slot="dropdown-menu" {...props} />;
}

export function DropdownMenuPortal({
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Portal>) {
	return <DropdownMenuPrimitive.Portal data-slot="dropdown-menu-portal" {...props} />;
}

export function DropdownMenuTrigger({
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Trigger>) {
	return <DropdownMenuPrimitive.Trigger data-slot="dropdown-menu-trigger" {...props} />;
}

export function DropdownMenuContent({
	className,
	sideOffset = 4,
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Content>) {
	return (
		<DropdownMenuPrimitive.Portal>
			<DropdownMenuPrimitive.Content
				data-slot="dropdown-menu-content"
				sideOffset={sideOffset}
				className={cn(
					"data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 z-50 max-h-(--radix-dropdown-menu-content-available-height) min-w-[8rem] origin-(--radix-dropdown-menu-content-transform-origin) overflow-y-auto overflow-x-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md data-[state=closed]:animate-out data-[state=open]:animate-in",
					className,
				)}
				{...props}
			/>
		</DropdownMenuPrimitive.Portal>
	);
}

export function DropdownMenuGroup({
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Group>) {
	return <DropdownMenuPrimitive.Group data-slot="dropdown-menu-group" {...props} />;
}

export function DropdownMenuItem({
	className,
	inset,
	variant = "default",
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Item> & {
	inset?: boolean;
	variant?: "default" | "destructive";
}) {
	return (
		<DropdownMenuPrimitive.Item
			data-slot="dropdown-menu-item"
			data-inset={inset}
			data-variant={variant}
			className={cn(
				"data-[variant=destructive]:*:[svg]:!text-destructive relative flex cursor-default select-none items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-hidden focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[inset]:pl-8 data-[variant=destructive]:text-destructive data-[disabled]:opacity-50 data-[variant=destructive]:focus:bg-destructive/10 data-[variant=destructive]:focus:text-destructive dark:data-[variant=destructive]:focus:bg-destructive/20 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground [&_svg]:pointer-events-none [&_svg]:shrink-0",
				className,
			)}
			{...props}
		/>
	);
}

export function DropdownMenuCheckboxItem({
	className,
	children,
	checked,
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.CheckboxItem>) {
	return (
		<DropdownMenuPrimitive.CheckboxItem
			data-slot="dropdown-menu-checkbox-item"
			className={cn(
				"relative flex cursor-default select-none items-center gap-2 rounded-sm py-1.5 pr-2 pl-8 text-sm outline-hidden focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50 [&_svg:not([class*='size-'])]:size-4 [&_svg]:pointer-events-none [&_svg]:shrink-0",
				className,
			)}
			checked={checked}
			{...props}
		>
			<span className="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">
				<DropdownMenuPrimitive.ItemIndicator>
					<CheckIcon className="size-4" />
				</DropdownMenuPrimitive.ItemIndicator>
			</span>
			{children}
		</DropdownMenuPrimitive.CheckboxItem>
	);
}

export function DropdownMenuRadioGroup({
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.RadioGroup>) {
	return <DropdownMenuPrimitive.RadioGroup data-slot="dropdown-menu-radio-group" {...props} />;
}

export function DropdownMenuRadioItem({
	className,
	children,
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.RadioItem>) {
	return (
		<DropdownMenuPrimitive.RadioItem
			data-slot="dropdown-menu-radio-item"
			className={cn(
				"relative flex cursor-default select-none items-center gap-2 rounded-sm py-1.5 pr-2 pl-8 text-sm outline-hidden focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50 [&_svg:not([class*='size-'])]:size-4 [&_svg]:pointer-events-none [&_svg]:shrink-0",
				className,
			)}
			{...props}
		>
			<span className="pointer-events-none absolute left-2 flex size-3.5 items-center justify-center">
				<DropdownMenuPrimitive.ItemIndicator>
					<DotFilledIcon className="size-2 fill-current" />
				</DropdownMenuPrimitive.ItemIndicator>
			</span>
			{children}
		</DropdownMenuPrimitive.RadioItem>
	);
}

export function DropdownMenuLabel({
	className,
	inset,
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Label> & {
	inset?: boolean;
}) {
	return (
		<DropdownMenuPrimitive.Label
			data-slot="dropdown-menu-label"
			data-inset={inset}
			className={cn("px-2 py-1.5 font-medium text-sm data-[inset]:pl-8", className)}
			{...props}
		/>
	);
}

export function DropdownMenuSeparator({
	className,
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Separator>) {
	return (
		<DropdownMenuPrimitive.Separator
			data-slot="dropdown-menu-separator"
			className={cn("-mx-1 my-1 h-px bg-border", className)}
			{...props}
		/>
	);
}

export function DropdownMenuShortcut({ className, ...props }: React.ComponentProps<"span">) {
	return (
		<span
			data-slot="dropdown-menu-shortcut"
			className={cn("ml-auto text-muted-foreground text-xs tracking-widest", className)}
			{...props}
		/>
	);
}

export function DropdownMenuSub({
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.Sub>) {
	return <DropdownMenuPrimitive.Sub data-slot="dropdown-menu-sub" {...props} />;
}

export function DropdownMenuSubTrigger({
	className,
	inset,
	children,
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.SubTrigger> & {
	inset?: boolean;
}) {
	return (
		<DropdownMenuPrimitive.SubTrigger
			data-slot="dropdown-menu-sub-trigger"
			data-inset={inset}
			className={cn(
				"flex cursor-default select-none items-center rounded-sm px-2 py-1.5 text-sm outline-hidden focus:bg-accent focus:text-accent-foreground data-[state=open]:bg-accent data-[inset]:pl-8 data-[state=open]:text-accent-foreground",
				className,
			)}
			{...props}
		>
			{children}
			<ChevronRightIcon className="ml-auto size-4" />
		</DropdownMenuPrimitive.SubTrigger>
	);
}

export function DropdownMenuSubContent({
	className,
	...props
}: React.ComponentProps<typeof DropdownMenuPrimitive.SubContent>) {
	return (
		<DropdownMenuPrimitive.SubContent
			data-slot="dropdown-menu-sub-content"
			className={cn(
				"data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 z-50 min-w-[8rem] origin-(--radix-dropdown-menu-content-transform-origin) overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-lg data-[state=closed]:animate-out data-[state=open]:animate-in",
				className,
			)}
			{...props}
		/>
	);
}
