// packages/ui/solidjs/src/components/input.tsx
import type { ComponentProps } from "solid-js";
import { splitProps } from "solid-js";

import { cn } from "@/libs/utils";

type InputProps = ComponentProps<"input">;

const Input = (props: InputProps) => {
	const [local, others] = splitProps(props, ["class"]);
	return (
		<input
			class={cn(
				"z-input w-full min-w-0 outline-none file:inline-flex file:border-0 file:bg-transparent file:text-foreground placeholder:text-muted-foreground disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50",
				local.class,
			)}
			data-slot="input"
			{...others}
		/>
	);
};

export { Input, type InputProps };

// packages/proto/ui/src/input.tsx
import { cn } from "@de100/ui-proto";

export function Input({
	className,
	type,
	...props
}: React.ComponentProps<"input">) {
	return (
		<input
			type={type}
			data-slot="input"
			className={cn(
				"file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
				"focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
				"aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
				className,
			)}
			{...props}
		/>
	);
}
