// packages/ui/domains/solidjs/src/components/label.tsx
import type { ComponentProps } from "solid-js";
import { splitProps } from "solid-js";

import { cn } from "#libs/utils";

type LabelProps = ComponentProps<"label">;

const Label = (props: LabelProps) => {
	const [local, others] = splitProps(props, ["class"]);

	return (
		// biome-ignore lint/a11y/noLabelWithoutControl: should be passed from the user, and we can't enforce it in this component
		<label
			class={cn(
				"z-label flex select-none items-center peer-disabled:cursor-not-allowed group-data-[disabled=true]:pointer-events-none",
				local.class,
			)}
			data-slot="label"
			{...others}
		/>
	);
};

export { Label };

// packages/proto/ui/src/label.tsx
"use client";

import { cn } from "@de100/ui-proto";
import { Label as LabelPrimitive } from "radix-ui";

export function Label({ className, ...props }: React.ComponentProps<typeof LabelPrimitive.Root>) {
	return (
		<LabelPrimitive.Root
			data-slot="label"
			className={cn(
				"flex select-none items-center gap-2 font-medium text-sm leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-50 group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50",
				className,
			)}
			{...props}
		/>
	);
}
