// packages/proto/ui/src/field.tsx
"use client";

import type { VariantProps } from "class-variance-authority";
import { useMemo } from "react";
import { cva } from "class-variance-authority";

import { cn } from "@de100/ui-proto";
import { Label } from "@de100/ui-proto/label";
import { Separator } from "@de100/ui-proto/separator";

export function FieldSet({
	className,
	...props
}: React.ComponentProps<"fieldset">) {
	return (
		<fieldset
			data-slot="field-set"
			className={cn(
				"flex flex-col gap-6",
				"has-[>[data-slot=checkbox-group]]:gap-3 has-[>[data-slot=radio-group]]:gap-3",
				className,
			)}
			{...props}
		/>
	);
}

export function FieldLegend({
	className,
	variant = "legend",
	...props
}: React.ComponentProps<"legend"> & { variant?: "legend" | "label" }) {
	return (
		<legend
			data-slot="field-legend"
			data-variant={variant}
			className={cn(
				"mb-3 font-medium",
				"data-[variant=legend]:text-base",
				"data-[variant=label]:text-sm",
				className,
			)}
			{...props}
		/>
	);
}

export function FieldGroup({
	className,
	...props
}: React.ComponentProps<"div">) {
	return (
		<div
			data-slot="field-group"
			className={cn(
				"group/field-group @container/field-group flex w-full flex-col gap-7 data-[slot=checkbox-group]:gap-3 [&>[data-slot=field-group]]:gap-4",
				className,
			)}
			{...props}
		/>
	);
}

const fieldVariants = cva(
	"group/field data-[invalid=true]:text-destructive flex w-full gap-3",
	{
		variants: {
			orientation: {
				vertical: ["flex-col [&>*]:w-full [&>.sr-only]:w-auto"],
				horizontal: [
					"flex-row items-center",
					"[&>[data-slot=field-label]]:flex-auto",
					"has-[>[data-slot=field-content]]:items-start has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
				],
				responsive: [
					"flex-col @md/field-group:flex-row @md/field-group:items-center [&>*]:w-full @md/field-group:[&>*]:w-auto [&>.sr-only]:w-auto",
					"@md/field-group:[&>[data-slot=field-label]]:flex-auto",
					"@md/field-group:has-[>[data-slot=field-content]]:items-start @md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
				],
			},
		},
		defaultVariants: {
			orientation: "vertical",
		},
	},
);

export function Field({
	className,
	orientation = "vertical",
	...props
}: React.ComponentProps<"div"> & VariantProps<typeof fieldVariants>) {
	return (
		// biome-ignore lint/a11y/useSemanticElements: <explanation> The div element is used here instead of a more semantic element like fieldset because it provides more flexibility in terms of styling and layout. The necessary ARIA attributes are applied to ensure accessibility. --- IGNORE ---
		<div
			role="group"
			data-slot="field"
			data-orientation={orientation}
			className={cn(fieldVariants({ orientation }), className)}
			{...props}
		/>
	);
}

export function FieldContent({
	className,
	...props
}: React.ComponentProps<"div">) {
	return (
		<div
			data-slot="field-content"
			className={cn(
				"group/field-content flex flex-1 flex-col gap-1.5 leading-snug",
				className,
			)}
			{...props}
		/>
	);
}

export function FieldLabel({
	className,
	...props
}: React.ComponentProps<typeof Label>) {
	return (
		<Label
			data-slot="field-label"
			className={cn(
				"group/field-label peer/field-label flex w-fit gap-2 leading-snug group-data-[disabled=true]/field:opacity-50",
				"has-[>[data-slot=field]]:w-full has-[>[data-slot=field]]:flex-col has-[>[data-slot=field]]:rounded-md has-[>[data-slot=field]]:border [&>*]:data-[slot=field]:p-4",
				"has-data-[state=checked]:bg-primary/5 has-data-[state=checked]:border-primary dark:has-data-[state=checked]:bg-primary/10",
				className,
			)}
			{...props}
		/>
	);
}

export function FieldTitle({
	className,
	...props
}: React.ComponentProps<"div">) {
	return (
		<div
			data-slot="field-label"
			className={cn(
				"flex w-fit items-center gap-2 text-sm leading-snug font-medium group-data-[disabled=true]/field:opacity-50",
				className,
			)}
			{...props}
		/>
	);
}

export function FieldDescription({
	className,
	...props
}: React.ComponentProps<"p">) {
	return (
		<p
			data-slot="field-description"
			className={cn(
				"text-muted-foreground text-sm leading-normal font-normal group-has-[[data-orientation=horizontal]]/field:text-balance",
				"last:mt-0 nth-last-2:-mt-1 [[data-variant=legend]+&]:-mt-1.5",
				"[&>a:hover]:text-primary [&>a]:underline [&>a]:underline-offset-4",
				className,
			)}
			{...props}
		/>
	);
}

export function FieldSeparator({
	children,
	className,
	...props
}: React.ComponentProps<"div"> & {
	children?: React.ReactNode;
}) {
	return (
		<div
			data-slot="field-separator"
			data-content={!!children}
			className={cn(
				"relative -my-2 h-5 text-sm group-data-[variant=outline]/field-group:-mb-2",
				className,
			)}
			{...props}
		>
			<Separator className="absolute inset-0 top-1/2" />
			{children && (
				<span
					className="bg-background text-muted-foreground relative mx-auto block w-fit px-2"
					data-slot="field-separator-content"
				>
					{children}
				</span>
			)}
		</div>
	);
}

export function FieldError({
	className,
	children,
	errors: maybeErrors,
	...props
}: React.ComponentProps<"div"> & {
	errors?: ({ message?: string } | undefined)[];
}) {
	const content = useMemo(() => {
		if (children) {
			return children;
		}

		const errors = (maybeErrors ?? []).filter((error) => error !== undefined);

		if (errors.length === 0) {
			return null;
		}

		if (errors.length === 1 && errors[0]?.message) {
			return errors[0].message;
		}

		return (
			<ul className="ml-4 flex list-disc flex-col gap-1">
				{errors.map(
					(error, index) =>
						error.message && <li key={index}>{error.message}</li>,
				)}
			</ul>
		);
	}, [children, maybeErrors]);

	if (!content) {
		return null;
	}

	return (
		<div
			role="alert"
			data-slot="field-error"
			className={cn("text-destructive text-sm font-normal", className)}
			{...props}
		>
			{content}
		</div>
	);
}

// packages/ui/solidjs/src/components/field.tsx
import type { VariantProps } from "class-variance-authority";
import { cva } from "class-variance-authority";
import type { ComponentProps, JSX } from "solid-js";
import { createMemo, For, Show, splitProps } from "solid-js";

import { cn } from "@/libs/utils";

import { Label } from "./label";
import { Separator } from "./separator";

type FieldSetProps = ComponentProps<"fieldset"> & {
	class?: string | undefined;
};

const FieldSet = (props: FieldSetProps) => {
	const [local, others] = splitProps(props, ["class"]);
	return (
		<fieldset
			class={cn("z-field-set flex flex-col", local.class)}
			data-slot="field-set"
			{...others}
		/>
	);
};

type FieldLegendProps = ComponentProps<"legend"> & {
	class?: string | undefined;
	variant?: "legend" | "label";
};

const FieldLegend = (props: FieldLegendProps) => {
	const [local, others] = splitProps(props, ["class", "variant"]);
	return (
		<legend
			class={cn("z-field-legend", local.class)}
			data-slot="field-legend"
			data-variant={local.variant ?? "legend"}
			{...others}
		/>
	);
};

type FieldGroupProps = ComponentProps<"div"> & {
	class?: string | undefined;
};

const FieldGroup = (props: FieldGroupProps) => {
	const [local, others] = splitProps(props, ["class"]);
	return (
		<div
			class={cn(
				"group/field-group @container/field-group z-field-group flex w-full flex-col",
				local.class,
			)}
			data-slot="field-group"
			{...others}
		/>
	);
};

const fieldVariants = cva("group/field z-field flex w-full", {
	variants: {
		orientation: {
			vertical: "z-field-orientation-vertical flex-col *:w-full [&>.sr-only]:w-auto",
			horizontal:
				"z-field-orientation-horizontal flex-row items-center has-[>[data-slot=field-content]]:items-start *:data-[slot=field-label]:flex-auto has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
			responsive:
				"z-field-orientation-responsive @md/field-group:flex-row flex-col @md/field-group:items-center *:w-full @md/field-group:*:w-auto @md/field-group:has-[>[data-slot=field-content]]:items-start @md/field-group:*:data-[slot=field-label]:flex-auto [&>.sr-only]:w-auto @md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
		},
	},
	defaultVariants: {
		orientation: "vertical",
	},
});

type FieldProps = ComponentProps<"div"> &
	VariantProps<typeof fieldVariants> & {
		class?: string | undefined;
	};

const Field = (props: FieldProps) => {
	const [local, others] = splitProps(props, ["class", "orientation"]);
	return (
		// biome-ignore lint/a11y/useSemanticElements: role="group" is intentional per shadcn design for accessibility
		<div
			class={cn(fieldVariants({ orientation: local.orientation }), local.class)}
			data-orientation={local.orientation ?? "vertical"}
			data-slot="field"
			role="group"
			{...others}
		/>
	);
};

type FieldContentProps = ComponentProps<"div"> & {
	class?: string | undefined;
};

const FieldContent = (props: FieldContentProps) => {
	const [local, others] = splitProps(props, ["class"]);
	return (
		<div
			class={cn(
				"group/field-content z-field-content flex flex-1 flex-col leading-snug",
				local.class,
			)}
			data-slot="field-content"
			{...others}
		/>
	);
};

type FieldLabelProps = ComponentProps<typeof Label> & {
	class?: string | undefined;
};

const FieldLabel = (props: FieldLabelProps) => {
	const [local, others] = splitProps(props, ["class"]);
	return (
		<Label
			class={cn(
				"group/field-label peer/field-label z-field-label flex w-fit leading-snug",
				"has-[>[data-slot=field]]:w-full has-[>[data-slot=field]]:flex-col",
				local.class,
			)}
			data-slot="field-label"
			{...others}
		/>
	);
};

type FieldTitleProps = ComponentProps<"div"> & {
	class?: string | undefined;
};

const FieldTitle = (props: FieldTitleProps) => {
	const [local, others] = splitProps(props, ["class"]);
	return (
		<div
			class={cn("z-field-title z-font-heading flex w-fit items-center leading-snug", local.class)}
			data-slot="field-label"
			{...others}
		/>
	);
};

type FieldDescriptionProps = ComponentProps<"p"> & {
	class?: string | undefined;
};

const FieldDescription = (props: FieldDescriptionProps) => {
	const [local, others] = splitProps(props, ["class"]);
	return (
		<p
			class={cn(
				"z-field-description font-normal leading-normal group-has-data-[orientation=horizontal]/field:text-balance",
				"nth-last-2:-mt-1 last:mt-0",
				"[&>a:hover]:text-primary [&>a]:underline [&>a]:underline-offset-4",
				local.class,
			)}
			data-slot="field-description"
			{...others}
		/>
	);
};

type FieldSeparatorProps = ComponentProps<"div"> & {
	class?: string | undefined;
	children?: JSX.Element;
};

const FieldSeparator = (props: FieldSeparatorProps) => {
	const [local, others] = splitProps(props, ["class", "children"]);
	return (
		<div
			class={cn("relative z-field-separator", local.class)}
			data-content={!!local.children}
			data-slot="field-separator"
			{...others}
		>
			<Separator class="absolute inset-0 top-1/2" />
			<Show when={local.children}>
				<span
					class="relative z-field-separator-content mx-auto block w-fit bg-background"
					data-slot="field-separator-content"
				>
					{local.children}
				</span>
			</Show>
		</div>
	);
};

type FieldErrorProps = ComponentProps<"div"> & {
	class?: string | undefined;
	children?: JSX.Element;
	errors?: Array<{ message?: string } | undefined>;
};

const FieldError = (props: FieldErrorProps) => {
	const [local, others] = splitProps(props, ["class", "children", "errors"]);

	const content = createMemo(() => {
		if (local.children) {
			return local.children;
		}

		if (!local.errors?.length) {
			return null;
		}

		const uniqueErrors = [
			...new Map(local.errors.map((error) => [error?.message, error])).values(),
		];

		if (uniqueErrors?.length === 1) {
			return uniqueErrors[0]?.message;
		}

		return (
			<ul class="ml-4 flex list-disc flex-col gap-1">
				<For each={uniqueErrors}>
					{(error) => (
						<Show when={error?.message}>
							<li>{error?.message}</li>
						</Show>
					)}
				</For>
			</ul>
		);
	});

	return (
		<Show when={content()}>
			<div
				class={cn("z-field-error font-normal", local.class)}
				data-slot="field-error"
				role="alert"
				{...others}
			>
				{content()}
			</div>
		</Show>
	);
};

export {
	Field,
	FieldContent,
	FieldDescription,
	FieldError,
	FieldGroup,
	FieldLabel,
	FieldLegend,
	FieldSeparator,
	FieldSet,
	FieldTitle,
	fieldVariants,
};
